### ISSUE TITLE
deviceMan.quitWebdriver() API report

### ISSUE THREAD

**Issue by b29201746** [farnking/Test-Dragon-Forum-of-TBots#15]
<details>
 <summary>Report Goes Here</summary>
Evaluating: self.API.deviceMan.quitWebdriver() did not finish after 3.00 seconds.
This may mean a number of things:
- This evaluation is really slow and this is expected.
    In this case it's possible to silence this error by raising the timeout, setting the
    PYDEVD_WARN_EVALUATION_TIMEOUT environment variable to a bigger value.

- The evaluation may need other threads running while it's running:
    In this case, it's possible to set the PYDEVD_UNBLOCK_THREADS_TIMEOUT
    environment variable so that if after a given timeout an evaluation doesn't finish,
    other threads are unblocked or you can manually resume all threads.

    Alternatively, it's also possible to skip breaking on a particular thread by setting a
    `pydev_do_not_trace = True` attribute in the related threading.Thread instance
    (if some thread should always be running and no breakpoints are expected to be hit in it).

- The evaluation is deadlocked:
    In this case you may set the PYDEVD_THREAD_DUMP_ON_WARN_EVALUATION_TIMEOUT
    environment variable to true so that a thread dump is shown along with this message and
    optionally, set the PYDEVD_INTERRUPT_THREAD_TIMEOUT to some value so that the debugger
    tries to interrupt the evaluation (if possible) when this happens.
[Thread-7][WARNING] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022B9552A948>: Failed to establish a new connection: [WinError 10061] 無法連線，因為目標電腦拒絕連線。')': /session/6d2c3c3d-4f08-4f3a-9628-e75b61c4d5cd/url
[Thread-7][WARNING] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022B9552AE88>: Failed to establish a new connection: [WinError 10061] 無法連線，因為目標電腦拒絕連線。')': /session/6d2c3c3d-4f08-4f3a-9628-e75b61c4d5cd/url

Traceback (most recent call last):
  File "c:\Users\Jiang\Desktop\TestDragonPlayGround\TestDragonDownload\rootPortable\python\lib\site-packages\urllib3\connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "c:\Users\Jiang\Desktop\TestDragonPlayGround\TestDragonDownload\rootPortable\python\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err
  File "c:\Users\Jiang\Desktop\TestDragonPlayGround\TestDragonDownload\rootPortable\python\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 無法連線，因為目標電腦拒絕連線。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Jiang\Desktop\TestDragonPlayGround\TestDragonDownload\rootPortable\python\lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "c:\Users\Jiang\Desktop\TestDragonPlayGround\TestDragonDownload\rootPortable\python\lib\site-packages\urllib3\connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "c:\Users\Jiang\Desktop\TestDragonPlayGround\TestDragonDownload\rootPortable\python\lib\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\client.py", line 1252, in request
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\client.py", line 1298, in _send_request
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\client.py", line 1247, in endheaders
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\client.py", line 1026, in _send_output
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\client.py", line 966, in send
  File "c:\Users\Jiang\Desktop\TestDragonPlayGround\TestDragonDownload\rootPortable\python\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "c:\Users\Jiang\Desktop\TestDragonPlayGround\TestDragonDownload\rootPortable\python\lib\site-packages\urllib3\connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000022B9551BE08>: Failed to establish a new connection: [WinError 10061] 無法連線，因為目標電腦拒絕連線。
</details>

**Comment by farnking** [comment]
你是已經開了一個webdriver嗎？要是沒有開任何webdriver就要去quit，那我們還沒處理這種情況。我再仔細看。
你可以把你的測試程式送來給我看嗎？

**Comment by b29201746** [comment]
已經解決了，跟在instantiateWebdriver()後執行就正常了

**Comment by farnking** [comment]
(^o^)
