### ISSUE TITLE
chromedriver.exe bug

### ISSUE THREAD

**Issue by durex002** [farnking/Test-Dragon-Forum-of-TBots#16]
在選好project
按下Test this project後動不了
<details>
<summary>報錯內容</summary>
'''bash
Starting the web test actioner!
Starting the webViewDictManager module!
Generating a random name:  PJrW2TBC3
webdrivermanager: creating downloadDir!
webDriverMan, using default driver path:  C:\Users\77qwe\Desktop\NTU\TestDragonDownload\rootPortable\TestDragonPlayGround\.TestDr
    The download folder is there!
webDriverMan, trying preset options!
webDriverMan, using preset options:  <selenium.webdriver.chrome.options.Options object at 0x0000028F25979548>
[Thread-2][INFO] ====== WebDriver manager ======
[Thread-2][INFO] Get LATEST chromedriver version for google-chrome 117.0.5938
[Thread-2][INFO] There is no [win32] chromedriver for browser 117.0.5938 in cache
[Thread-2][INFO] Get LATEST chromedriver version for google-chrome 117.0.5938
[Thread-2][INFO] About to download new driver from https://chromedriver.storage.googleapis.com/117.0.5938/chromedriver_win32.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1449  100  1449    0     0   1530      0 --:--:-- --:--:-- --:--:--  1534
tar: Error opening archive: Unrecognized archive format
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\farn\Documents\prgm\TestDragon\Server\clientDownloads\TestDragon77qweasdzxc@gmail.com\TestDragonPlayGround\src\C
  File "C:\Users\77qwe\Desktop\NTU\TestDragonDownload\rootPortable\python\lib\site-packages\webdriver_manager\chrome.py", line 39
    driver_path = self._get_driver_path(self.driver)
  File "C:\Users\77qwe\Desktop\NTU\TestDragonDownload\rootPortable\python\lib\site-packages\webdriver_manager\core\manager.py", l
    file = self._download_manager.download_file(driver.get_url())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\77qwe\Desktop\NTU\TestDragonDownload\rootPortable\python\lib\site-packages\selenium\webdriver\common\service.py", line 79, in start
    creationflags=self.creationflags)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 800, in __init__
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 1207, in _execute_child
FileNotFoundError: [WinError 2] 系統找不到指定的檔案。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\threading.py", line 926, in _bootstrap_inner
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\threading.py", line 870, in run
  File "C:\Users\farn\Documents\prgm\TestDragon\Server\clientDownloads\TestDragon77qweasdzxc@gmail.com\TestDragonPlayGround\src\CnTestingTask.pyx", line 33609, in startMegaTBot
  File "C:\Users\farn\Documents\prgm\TestDragon\Server\clientDownloads\TestDragon77qweasdzxc@gmail.com\TestDragonPlayGround\src\CnTestingTask.pyx", line 39790, in __init__
  File "C:\Users\farn\Documents\prgm\TestDragon\Server\clientDownloads\TestDragon77qweasdzxc@gmail.com\TestDragonPlayGround\src\CnTestingTask.pyx", line 29800, in __init__
  File "C:\Users\farn\Documents\prgm\TestDragon\Server\clientDownloads\TestDragon77qweasdzxc@gmail.com\TestDragonPlayGround\src\CnTestingTask.pyx", line 71220, in __init__
  File "C:\Users\farn\Documents\prgm\TestDragon\Server\clientDownloads\TestDragon77qweasdzxc@gmail.com\TestDragonPlayGround\src\CnTestingTask.pyx", line 71281, in start
  File "C:\Users\farn\Documents\prgm\TestDragon\Server\clientDownloads\TestDragon77qweasdzxc@gmail.com\TestDragonPlayGround\src\CnTestingTask.pyx", line 15327, in webDriverManagerFromForum  
  File "C:\Users\farn\Documents\prgm\TestDragon\Server\clientDownloads\TestDragon77qweasdzxc@gmail.com\TestDragonPlayGround\src\CnTestingTask.pyx", line 13349, in __init__
  File "C:\Users\77qwe\Desktop\NTU\TestDragonDownload\rootPortable\python\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 72, in __init__
    service_log_path, service, keep_alive)
  File "C:\Users\77qwe\Desktop\NTU\TestDragonDownload\rootPortable\python\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 90, in __init__
    self.service.start()
  File "C:\Users\77qwe\Desktop\NTU\TestDragonDownload\rootPortable\python\lib\site-packages\selenium\webdriver\common\service.py", line 86, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home
'''
</details>

**Comment by farnking** [comment]
你是選那個計劃呢？

**Comment by SYuan0314** [comment]
project 是 134,Test-Dragon,test dragon 1,web,chrome

<details>
<summary>debug console<summary>

```bash
Exception has occurred: WebDriverException
Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home
  File "C:\Users\farn\Documents\prgm\TestDragon\Server\clientDownloads\TestDragon77qweasdzxc@gmail.com\TestDragonPlayGround\src\CnTestingTask.pyx", line 13337, in __init__
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/117.0.5938/chromedriver_win32.zip

During handling of the above exception, another exception occurred:

  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 800, in __init__
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 1207, in _execute_child
FileNotFoundError: [WinError 2] 系統找不到指定的檔案。

During handling of the above exception, another exception occurred:

  File "C:\Users\farn\Documents\prgm\TestDragon\Server\clientDownloads\TestDragon77qweasdzxc@gmail.com\TestDragonPlayGround\src\CnTestingTask.pyx", line 13346, in __init__
  File "C:\Users\farn\Documents\prgm\TestDragon\Server\clientDownloads\TestDragon77qweasdzxc@gmail.com\TestDragonPlayGround\src\CnTestingTask.pyx", line 15324, in webDriverManagerFromForum
  File "C:\Users\farn\Documents\prgm\TestDragon\Server\clientDownloads\TestDragon77qweasdzxc@gmail.com\TestDragonPlayGround\src\CnTestingTask.pyx", line 71278, in start
  File "C:\Users\farn\Documents\prgm\TestDragon\Server\clientDownloads\TestDragon77qweasdzxc@gmail.com\TestDragonPlayGround\src\CnTestingTask.pyx", line 71217, in __init__
  File "C:\Users\farn\Documents\prgm\TestDragon\Server\clientDownloads\TestDragon77qweasdzxc@gmail.com\TestDragonPlayGround\src\CnTestingTask.pyx", line 29797, in __init__
  File "C:\Users\farn\Documents\prgm\TestDragon\Server\clientDownloads\TestDragon77qweasdzxc@gmail.com\TestDragonPlayGround\src\CnTestingTask.pyx", line 39787, in __init__
  File "C:\Users\farn\Documents\prgm\TestDragon\Server\clientDownloads\TestDragon77qweasdzxc@gmail.com\TestDragonPlayGround\src\CnTestingTask.pyx", line 33606, in startMegaTBot
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\threading.py", line 870, in run
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\threading.py", line 926, in _bootstrap_inner
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\threading.py", line 890, in _bootstrap
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home
```

<details>

<details>
<summary>terminal<summary>

```bash
webdrivermanager: creating downloadDir!
webDriverMan, using default driver path:  C:\Users\77qwe\Desktop\NTU\TestDragonDownload\rootPortable\TestDragonPlayGround\.TestDragonCache\webdrivers
    The download folder is there!
webDriverMan, trying preset options!
webDriverMan, using preset options:  <selenium.webdriver.chrome.options.Options object at 0x0000014988C65788>
[Thread-7][INFO] ====== WebDriver manager ======
[Thread-7][INFO] Get LATEST chromedriver version for google-chrome 117.0.5938
[Thread-7][INFO] There is no [win32] chromedriver for browser 117.0.5938 in cache
[Thread-7][INFO] Get LATEST chromedriver version for google-chrome 117.0.5938
[Thread-7][INFO] About to download new driver from https://chromedriver.storage.googleapis.com/117.0.5938/chromedriver_win32.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1449  100  1449    0     0   1603      0 --:--:-- --:--:-- --:--:--  1608
tar: Error opening archive: Unrecognized archive format
```

<details>
