### ISSUE TITLE
gAutoMan seman can not be

### ISSUE THREAD

**Issue by SYuan0314** [farnking/Test-Dragon-Forum-of-TBots#18]
**Describe the bug**
when I use any API about 'gAutoMan' (or 'seman') 
it returns has no attribute 'gAutoMan' (or 'seman') 

**Project ID** 
111,

**Name of App under Test**
 pcgamer.com

**Type of App under Test**
windows(firefox)

**URL**
https://forums.pcgamer.com/

**To Reproduce**

just call self.API.gAutoMan.......
or
call self.API.seman.....
 

**Dumping text from terminal or console** 
<details>
<summary>debug console</summary>

```bash

self.API.gAutoMan.getNextMostLikelyAction()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'CnTestDragonAPI_CnTestDragonAPI' object has no attribute 'gAutoMan'

```

</details>

<details>
<summary>debug console</summary>

```bash

self.API.seman.queryHottestFormTopic()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'CnTestDragonAPI_CnTestDragonAPI' object has no attribute 'seman'

```

</details>

**Your diagnosis**
these two API name may be changed

**Comment by farnking** [comment]
書沅，你可以說明你是在什麼情況下去呼叫這個API呢？
因為這個API應該是要先呼叫了self.API.gAutoMan.getMostLikelyAction()，才能呼叫這個self.API.gAutoMan.getNextMostLikelyAction()，否則行為可能無法預測。
而且要能呼叫self.API.gAutoMan.getMostLikelyAction()，可能也有些特殊的use case才能，也就是要先能夠建立generalized automata後。

因此我們確實應該要送出警告訊息panel，
你可以幫忙的就是告訴我你是在什麼情況下去呼叫這個API，請說明。
