### ISSUE TITLE
python 3.9 在選擇project後卡住

### ISSUE THREAD

**Issue by SYuan0314** [farnking/Test-Dragon-Forum-of-TBots#29]
**Describe the bug**
python 3.9 在選擇project後卡住

**Project ID** 
For your management

**Type of App under Test**
chrome

**URL**
ebay.com

**To Reproduce**
1.下載python3.9 並下載完34個缺少套件
2.登入testdragon並選擇project 92
3.卡住

**Screenshots**
![image](https://github.com/farnking/Test-Dragon-Forum-of-TBots/assets/82447912/b3c7d365-b126-4c0b-a882-bbfe7b8192a0)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser :chrome
 - Version :119.0.6045.105

**Dumping text from terminal or console** 
```bash=
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\77qwe\anaconda3\envs\NbIYKynmKz20231106074838\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\77qwe\anaconda3\envs\NbIYKynmKz20231106074838\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\farn\Documents\prgm\TestDragon\Server\clientDownloads\TestDragon77qweasdzxc@gmail.com\TestDragonPlayGround\src\CnTestingTask.pyx", line 33981, in startMegaTBot
  File "C:\Users\farn\Documents\prgm\TestDragon\Server\clientDownloads\TestDragon77qweasdzxc@gmail.com\TestDragonPlayGround\src\CnTestingTask.pyx", line 40202, in __init__
  File "C:\Users\farn\Documents\prgm\TestDragon\Server\clientDownloads\TestDragon77qweasdzxc@gmail.com\TestDragonPlayGround\src\CnTestingTask.pyx", line 31395, in __init__
  File "C:\Users\farn\Documents\prgm\TestDragon\Server\clientDownloads\TestDragon77qweasdzxc@gmail.com\TestDragonPlayGround\src\CnTestingTask.pyx", line 31523, in recordNewState
  File "C:\Users\farn\Documents\prgm\TestDragon\Server\clientDownloads\TestDragon77qweasdzxc@gmail.com\TestDragonPlayGround\src\CnTestingTask.pyx", line 31195, in addState
  File "C:\Users\farn\Documents\prgm\TestDragon\Server\clientDownloads\TestDragon77qweasdzxc@gmail.com\TestDragonPlayGround\src\CnTestingTask.pyx", line 26992, in __init__
  File "C:\Users\farn\Documents\prgm\TestDragon\Server\clientDownloads\TestDragon77qweasdzxc@gmail.com\TestDragonPlayGround\src\CnTestingTask.pyx", line 28651, in getStateIR
  File "C:\Users\farn\Documents\prgm\TestDragon\Server\clientDownloads\TestDragon77qweasdzxc@gmail.com\TestDragonPlayGround\src\CnTestingTask.pyx", line 29370, in recDict
  File "C:\Users\farn\Documents\prgm\TestDragon\Server\clientDownloads\TestDragon77qweasdzxc@gmail.com\TestDragonPlayGround\src\CnTestingTask.pyx", line 29541, in recDictInOneIFrame
  File "C:\Users\farn\Documents\prgm\TestDragon\Server\clientDownloads\TestDragon77qweasdzxc@gmail.com\TestDragonPlayGround\src\CnTestingTask.pyx", line 29541, in recDictInOneIFrame
  File "C:\Users\farn\Documents\prgm\TestDragon\Server\clientDownloads\TestDragon77qweasdzxc@gmail.com\TestDragonPlayGround\src\CnTestingTask.pyx", line 29541, in recDictInOneIFrame
  [Previous line repeated 6 more times]
  File "C:\Users\farn\Documents\prgm\TestDragon\Server\clientDownloads\TestDragon77qweasdzxc@gmail.com\TestDragonPlayGround\src\CnTestingTask.pyx", line 29397, in recDictInOneIFrame
  File "C:\Users\farn\Documents\prgm\TestDragon\Server\clientDownloads\TestDragon77qweasdzxc@gmail.com\TestDragonPlayGround\src\CnTestingTask.pyx", line 69449, in getViewDict
  File "C:\Users\farn\Documents\prgm\TestDragon\Server\clientDownloads\TestDragon77qweasdzxc@gmail.com\TestDragonPlayGround\src\CnTestingTask.pyx", line 69738, in getCVImageFromElement
  File "C:\Users\farn\Documents\prgm\TestDragon\Server\clientDownloads\TestDragon77qweasdzxc@gmail.com\TestDragonPlayGround\src\CnTestingTask.pyx", line 11007, in getPngDataCropImg
AttributeError: 'CnTestDragonTask' object has no attribute 'cnQueryFlagDumpCroppedPngData'
[192500:261668:1106/182059.646:ERROR:stun_port.cc(79)] Binding error response: class=4 number=1 reason=Unauthorized
[192500:261668:1106/182101.278:ERROR:stun_port.cc(79)] Binding error response: class=4 number=1 reason=Unauthorized
[192500:261668:1106/182109.797:ERROR:stun_port.cc(79)] Binding error response: class=4 number=1 reason=Unauthorized
[192500:261668:1106/182111.439:ERROR:stun_port.cc(79)] Binding error response: class=4 number=1 reason=Unauthorized
[192500:261668:1106/182119.947:ERROR:stun_port.cc(79)] Binding error response: class=4 number=1 reason=Unauthorized
[192500:261668:1106/182121.590:ERROR:stun_port.cc(79)] Binding error response: class=4 number=1 reason=Unauthorized
[192500:261668:1106/182130.143:ERROR:stun_port.cc(79)] Binding error response: class=4 number=1 reason=Unauthorized
[192500:261668:1106/182131.755:ERROR:stun_port.cc(79)] Binding error response: class=4 number=1 reason=Unauthorized
[192500:261668:1106/182140.298:ERROR:stun_port.cc(79)] Binding error response: class=4 number=1 reason=Unauthorized
[192500:261668:1106/182141.909:ERROR:stun_port.cc(79)] Binding error response: class=4 number=1 reason=Unauthorized
```

**Comment by farnking** [comment]
應該改好了。

**Comment by SYuan0314** [comment]
沒問題了 感恩
