### ISSUE TITLE
被強制更新完之後就無法打開 Test Dragon

### ISSUE THREAD

**Issue by ChiHaoLu** [farnking/Test-Dragon-Forum-of-TBots#37]
原本可以正常使用，但剛剛重開被強制更新之後就無法使用

```
ERROR:
Can't load module 7z.dll
==(pathEqual  0 )==
p1:  C:\Users\qazws\Downloads\TestDragonPlayGround\tmpTestDragon\TestDragonPlayGround
p2:  C:\Users\qazws\Downloads\TestDragonPlayGround
==(pathEqual  1 )==
p1:  C:\Users\qazws\Downloads\TestDragonPlayGround\tmpTestDragon
p2:  C:\Users\qazws\Downloads
(^o^) haha I got the file!
TestDragon leaving login mainLoop 2!
on close windows
evtObjLabel:  TEST-DRAGON 0.95.10 20231220
Failure reading enrypted test traces!  It is not there!
Warning: global project used before initialization.
Seems that the GUI is not ready!
'NoneType' object has no attribute 'postMessageInDialogPanel'
I think queryShellTBot() is not ready!
'CnTestDragonTask' object has no attribute '_CnTestDragonTask__shellTBot'
Seems that the GUI is not ready!
'NoneType' object has no attribute 'postMessageInDialogPanel'
>>> 1.23: before addTestLog: {'player': 'r12921105@ntu.edu.tw', 'type': 'notification', 'contents': ['TestDragon new version (0-9
>>> 1.25 TestDragon: seems the issue manager is not ready!
'CnTestDragonTask' object has no attribute '_CnTestDragonTask__issueManager'
{'player': 'r12921105@ntu.edu.tw', 'type': 'notification', 'contents': ['TestDragon new version (0-96-0) downloaded!\nPlease restart TestDragon!!'], 'time': '18:12:24', 'date': '12/25/23'}
********************
>>> 1.26: before returning from api.addIssueReport()
Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Users\qazws\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\qazws\AppData\Local\Programs\Python\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\farn\Documents\prgm\TestDragon\Server\clientDownloads\TestDragonr12921105@ntu.edu.tw\TestDragonDownload39_Windows\rootPortable\TestDragonPlayGround\src\CnTestingTask.pyx", line 1629, in asyncVoice
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\qazws\\Downloads\\TestDragonPlayGround\\.TestDragonCache\\mp3Test2.mp3'
on close windows
evtObjLabel:  TestDragon congratulations!
TestDragon exits in TestDragon pyc update!
```

已嘗試過重開數次皆無用

python 版本為 3.9.7，OS 為 WIndows11 64 位元

**Comment by farnking** [comment]
你可以先試著從網路重新下載一次嗎？
然後幫我檢查這個檔案在不在，是不是能夠手動播放這個MP3檔案？
 'C:\\Users\\qazws\\Downloads\\TestDragonPlayGround\\.TestDragonCache\\mp3Test2.mp3'

**Comment by ChiHaoLu** [comment]
檔案在，可以手動播放

**Comment by farnking** [comment]
網路重新下載試試看

**Comment by ChiHaoLu** [comment]
下載網路上最新版的完是一樣的錯誤, 都是 mp3 檔的 permission error

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\qazws\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\qazws\AppData\Local\Programs\Python\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\farn\Documents\prgm\TestDragon\Server\clientDownloads\TestDragonr12921105@ntu.edu.tw\TestDragonDownload39_Windows\rootPortable\TestDragonPlayGround\src\CnTestingTask.pyx", line 1629, in asyncVoice
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\qazws\\Downloads\\GAB\\TestDragonPlayGround\\.TestDragonCache\\mp3Test0.mp3'
```

**Comment by farnking** [comment]
你可以幫我查察看這個檔案的使用權限嗎？
C:\\Users\\qazws\\Downloads\\GAB\\TestDragonPlayGround\\.TestDragonCache\\mp3Test0.mp

你是使用windows嗎？

**Comment by farnking** [comment]
你可以試著重覆執行幾遍看嗎？我在找出原因。我這邊方才有出現這錯誤，結果我重做一次，他又沒了。

**Comment by farnking** [comment]
剛才放了新版上去，請重新點擊桌面T39執行，
要是失敗，就請重新網路下載，執行CnTestDragonSetup.bat後，再點擊桌面T39執行。
